// KANJI[char] = [on readings, kun readings, meaning, radical/component breakdown]
const KANJI = {
  // ---- Food group ----
  '固': ['コ', 'かた(い) かた(める)', 'hard, firm', '囗 enclosure + 古 old'],
  '柔': ['ジュウ ニュウ', 'やわ(らかい)', 'soft, gentle', '矛 spear + 木 tree'],
  '普': ['フ', '', 'universal, common', '並 (line up) over 日 sun'],
  '通': ['ツウ ツ', 'とお(る) かよ(う)', 'pass through, commute', '辶 road + 甬'],
  '濃': ['ノウ', 'こ(い)', 'thick, dark, rich', '氵 water + 農 farming'],
  '薄': ['ハク', 'うす(い)', 'thin, light, weak', '艹 grass + 氵 water + 専'],
  '多': ['タ', 'おお(い)', 'many', '夕 evening, doubled'],
  '少': ['ショウ', 'すく(ない) すこ(し)', 'few, a little', '小 small + ノ stroke'],
  '抜': ['バツ', 'ぬ(く) ぬ(ける)', 'pull out, omit', '扌 hand + 友 friend'],
  '替': ['タイ', 'か(える) か(わる)', 'replace, exchange', '夫夫 over 日 sun'],
  '玉': ['ギョク', 'たま', 'ball, jewel', '王 king + 丶 dot'],
  '大': ['ダイ タイ', 'おお(きい) おお', 'big', 'person with arms outstretched'],
  '盛': ['セイ ジョウ', 'も(る) さか(る)', 'heap up, prosper', '成 + 皿 dish'],
  '豚': ['トン', 'ぶた', 'pig', '月 flesh + 豕 pig'],
  '骨': ['コツ', 'ほね', 'bone', '骨 (radical itself)'],
  '醤': ['ショウ', '', 'fermented sauce (soy)', '将 + 酉 fermenting jar'],
  '油': ['ユ', 'あぶら', 'oil', '氵 water + 由'],
  '味': ['ミ', 'あじ あじ(わう)', 'taste', '口 mouth + 未'],
  '噌': ['ソウ', 'かまびす(しい)', 'noisy (used in 味噌 miso)', '口 mouth + 曾'],
  '塩': ['エン', 'しお', 'salt', '土 earth + salt-pan 皿 (simplified from 鹽)'],
  '麺': ['メン', '', 'noodles', '麦 wheat + 面 face'],
  '家': ['カ ケ', 'いえ や うち', 'house, family', '宀 roof + 豕 pig'],
  '系': ['ケイ', '', 'lineage, system', '糸 thread'],
  '叉': ['サ シャ', 'また', 'fork, crossing', '又 hand + 丶'],
  '焼': ['ショウ', 'や(く) や(ける)', 'bake, grill, burn', '火 fire + 尭'],
  '煮': ['シャ', 'に(る) に(える)', 'simmer, boil', '者 + 灬 fire'],
  '卵': ['ラン', 'たまご', 'egg', 'picture of an egg/roe'],
  '海': ['カイ', 'うみ', 'sea', '氵 water + 毎'],
  '苔': ['タイ', 'こけ', 'moss, lichen (seaweed in 海苔)', '艹 grass + 台'],
  '木': ['モク ボク', 'き こ', 'tree, wood', 'picture of a tree'],
  '耳': ['ジ', 'みみ', 'ear', 'picture of an ear'],
  '白': ['ハク ビャク', 'しろ しろ(い)', 'white', ''],
  '飯': ['ハン', 'めし', 'cooked rice, meal', '飠 food + 反'],
  '生': ['セイ ショウ', 'い(きる) う(まれる) は(える) なま き', 'life, raw, birth', 'picture of a sprout'],
  '日': ['ニチ ジツ', 'ひ か', 'sun, day', 'picture of the sun'],
  '本': ['ホン', 'もと', 'book, origin', '木 tree + 一 root mark'],
  '酒': ['シュ', 'さけ さか', 'alcohol, sake', '氵 water + 酉 fermenting jar'],
  '酎': ['チュウ', '', 'distilled liquor', '酉 fermenting jar + 寸'],
  '枝': ['シ', 'えだ', 'branch', '木 tree + 支'],
  '豆': ['トウ ズ', 'まめ', 'bean', 'picture of a bean vessel'],
  '鳥': ['チョウ', 'とり', 'bird', 'picture of a bird'],
  '唐': ['トウ', 'から', 'Tang China, foreign', '庚 + 口 mouth'],
  '揚': ['ヨウ', 'あ(げる) あ(がる)', 'raise, deep-fry', '扌 hand + 昜'],
  '餃': ['ギョウ コウ', '', 'dumpling', '飠 food + 交'],
  '子': ['シ ス', 'こ', 'child', 'picture of a child'],
  '刺': ['シ', 'さ(す) さ(さる)', 'stab, pierce', '朿 thorn + 刂 knife'],
  '身': ['シン', 'み', 'body, flesh', 'picture of a body'],
  '串': ['カン', 'くし', 'skewer', 'two items on a skewer'],
  '皮': ['ヒ', 'かわ', 'skin, hide', 'hand peeling a hide'],
  '砂': ['サ シャ', 'すな', 'sand', '石 stone + 少'],
  '肝': ['カン', 'きも', 'liver', '月 flesh + 干'],
  '手': ['シュ', 'て', 'hand', 'picture of a hand'],
  '羽': ['ウ', 'は はね', 'feather, wing', 'two wings'],
  '先': ['セン', 'さき', 'ahead, tip, previous', '生 sprout + 儿 legs'],
  '軟': ['ナン', 'やわ(らかい)', 'soft', '車 + 欠'],
  '牛': ['ギュウ', 'うし', 'cow', 'picture of a cow'],
  '網': ['モウ', 'あみ', 'net', '糸 thread + 罔'],
  '鮪': ['ユウ', 'まぐろ しび', 'tuna', '魚 fish + 有'],
  '赤': ['セキ シャク', 'あか あか(い)', 'red', ''],
  '中': ['チュウ', 'なか', 'middle, inside', '口 with a line through it'],
  '鮭': ['ケイ', 'さけ しゃけ', 'salmon', '魚 fish + 圭'],
  '老': ['ロウ', 'お(いる) ふ(ける)', 'old age', 'bent old person with cane'],
  '烏': ['ウ', 'からす', 'crow', 'picture of a crow'],
  '賊': ['ゾク', '', 'thief, rebel', '貝 shell/money + 戎'],
  '蛸': ['ショウ', 'たこ', 'octopus', '虫 insect/creature + 肖'],
  '軍': ['グン', '', 'army', '冖 cover + 車 chariot'],
  '艦': ['カン', '', 'warship', '舟 boat + 監'],
  '蕎': ['キョウ', 'そば', 'buckwheat', '艹 grass + 喬'],
  '麦': ['バク', 'むぎ', 'wheat, barley', 'picture of a wheat plant'],
  '温': ['オン', 'あたた(かい) あたた(める)', 'warm', '氵 water + 昷'],
  '冷': ['レイ', 'つめ(たい) ひ(える) さ(ます)', 'cold', '冫 ice + 令'],
  '天': ['テン', 'あめ あま', 'heaven, sky', '大 person with 一 above'],
  '狐': ['コ', 'きつね', 'fox', '犭 animal + 瓜 (sound)'],
  '狸': ['リ', 'たぬき', 'raccoon dog', '犭 animal + 里 (sound)'],
  '洋': ['ヨウ', '', 'ocean, Western', '氵 water + 羊 (sound)'],
  '食': ['ショク ジキ', 'た(べる) く(う)', 'eat, food', '人 + 良'],
  '丼': ['トン ドン', 'どんぶり', 'bowl, rice-bowl dish', '井 well frame + 丶 dot'],
  '穴': ['ケツ', 'あな', 'hole', '宀 cover + 八'],
  '南': ['ナン', 'みなみ', 'south', ''],
  '瓜': ['カ', 'うり', 'melon, gourd', 'picture of a gourd on a vine'],
  '茄': ['カ', '', 'eggplant', '艹 grass + 加'],
  '並': ['ヘイ', 'なみ なら(べる)', 'line up, ordinary', 'two people side by side'],
  '頭': ['トウ ズ ト', 'あたま かしら', 'head', '豆 + 頁 head'],
  '特': ['トク', '', 'special', '牛 cow + 寺 temple'],
  '紅': ['コウ ク', 'べに くれない', 'crimson', '糸 thread + 工'],
  '姜': ['キョウ', '', 'ginger (in 生姜)', '羊 sheep + 女 woman'],
  '七': ['シチ', 'なな なな(つ)', 'seven', ''],
  '好': ['コウ', 'この(む) す(く)', 'like, fond of', '女 woman + 子 child'],
  '鉄': ['テツ', '', 'iron', '金 metal + 失'],
  '板': ['ハン バン', 'いた', 'board, plate', '木 wood + 反'],
  '鮮': ['セン', 'あざ(やか)', 'fresh, vivid', '魚 fish + 羊 sheep'],
  '青': ['セイ ショウ', 'あお あお(い)', 'blue, green', ''],
  '鰹': ['ケン', 'かつお', 'bonito', '魚 fish + 堅 hard'],
  '節': ['セツ セチ', 'ふし', 'joint, season, section', '竹 bamboo + 即'],

  // ---- Menu Essentials group ----
  '券': ['ケン', '', 'ticket, coupon', '𠂊 + 刀 knife (split tally)'],
  '定': ['テイ ジョウ', 'さだ(める) さだ(まる)', 'decide, fixed', '宀 roof + 正 correct'],
  '単': ['タン', '', 'single, simple', ''],
  '品': ['ヒン', 'しな', 'goods, quality', '口 mouth × 3'],
  '放': ['ホウ', 'はな(す) はな(つ)', 'release, let go', '方 + 攵 tap'],
  '題': ['ダイ', '', 'topic, title', '是 + 頁 head'],
  '飲': ['イン', 'の(む)', 'drink', '飠 food + 欠 yawn'],
  '持': ['ジ', 'も(つ)', 'hold, have', '扌 hand + 寺 temple'],
  '帰': ['キ', 'かえ(る) かえ(す)', 'return home', ''],
  '会': ['カイ エ', 'あ(う)', 'meet, association', ''],
  '計': ['ケイ', 'はか(る) はか(らう)', 'measure, plan', '言 words + 十 ten'],
  '税': ['ゼイ', '', 'tax', '禾 grain + 兌'],
  '込': ['', 'こ(む) こ(める)', 'be included, crowded', '辶 road + 入 enter (Japan-made kanji)'],
  '禁': ['キン', '', 'prohibit', '林 woods + 示 altar'],
  '煙': ['エン', 'けむり けむ(る)', 'smoke', '火 fire + 垔'],
  '席': ['セキ', '', 'seat', ''],
  '喫': ['キツ', '', 'consume (drink, smoke)', '口 mouth + 契'],
  '代': ['ダイ タイ', 'か(わる) か(える) よ しろ', 'substitute, era', '亻 person + 弋'],
  '追': ['ツイ', 'お(う)', 'chase, add on', '辶 road + 𠂤'],
  '加': ['カ', 'くわ(える) くわ(わる)', 'add', '力 power + 口 mouth'],
  '予': ['ヨ', 'あらかじ(め)', 'beforehand', ''],
  '約': ['ヤク', '', 'promise, approx.', '糸 thread + 勺'],
  '無': ['ム ブ', 'な(い)', 'nothing, without', ''],
  '料': ['リョウ', '', 'fee, ingredient', '米 rice + 斗 measure'],
  '注': ['チュウ', 'そそ(ぐ)', 'pour, note, order', '氵 water + 主'],
  '文': ['ブン モン', 'ふみ', 'sentence, writing', ''],
  '親': ['シン', 'おや した(しい)', 'parent, intimate', '立 + 木 + 見'],
  '汁': ['ジュウ', 'しる', 'juice, soup', '氵 water + 十'],
  '漬': ['シ', 'つ(ける) つ(かる)', 'pickle, soak', '氵 water + 責'],
  '物': ['ブツ モツ', 'もの', 'thing', '牛 cow + 勿'],
  '納': ['ノウ ナッ ナ ナン トウ', 'おさ(める) おさ(まる)', 'store, pay, supply', '糸 thread + 内'],
  '魚': ['ギョ', 'さかな うお', 'fish', 'picture of a fish'],
  '鰻': ['マン', 'うなぎ', 'eel', '魚 fish + 曼'],
  '寿': ['ジュ', 'ことぶき', 'longevity, celebration', ''],
  '司': ['シ', '', 'manage, official', ''],
  '握': ['アク', 'にぎ(る)', 'grip, grasp', '扌 hand + 屋'],
  '巻': ['カン', 'ま(く) まき', 'roll, volume', ''],
  '鯛': ['チョウ', 'たい', 'sea bream', '魚 fish + 周'],
  '鰤': ['', 'ぶり', 'yellowtail', '魚 fish + 師'],
  '鯖': ['セイ', 'さば', 'mackerel', '魚 fish + 青'],
  '雲': ['ウン', 'くも', 'cloud', '雨 rain + 云'],
  '丹': ['タン', 'に', 'cinnabar red', ''],
  '帆': ['ハン', 'ほ', 'sail', '巾 cloth + 凡'],
  '立': ['リツ リュウ', 'た(つ) た(てる)', 'stand up', 'person standing on ground'],
  '回': ['カイ エ', 'まわ(る) まわ(す)', 'turn, times', ''],
  '転': ['テン', 'ころ(ぶ) ころ(がる)', 'roll, turn', '車 wheel + 云'],
  '山': ['サン', 'やま', 'mountain', 'picture of peaks'],
  '葵': ['キ', 'あおい', 'hollyhock', '艹 grass + 癸'],
  '龍': ['リュウ', 'たつ', 'dragon', ''],
  '茶': ['チャ サ', '', 'tea', '艹 grass + 人 + 木'],
  '梅': ['バイ', 'うめ', 'plum (ume)', '木 tree + 毎'],
  '熱': ['ネツ', 'あつ(い)', 'heat, fever', '灬 fire + 埶'],
  '燗': ['カン', '', 'warming sake', '火 fire + 間'],
  '水': ['スイ', 'みず', 'water', 'picture of flowing water'],
  '辛': ['シン', 'から(い) つら(い)', 'spicy; painful, hard', ''],
  '甘': ['カン', 'あま(い) あま(える)', 'sweet', ''],
  '酸': ['サン', 'す(い)', 'acid, sour', '酉 fermenting jar + 夋'],
  '苦': ['ク', 'にが(い) くる(しい)', 'bitter, painful', '艹 grass + 古'],
  '美': ['ビ', 'うつく(しい)', 'beautiful', '羊 sheep + 大'],
  '蒸': ['ジョウ', 'む(す) む(らす)', 'steam', '艹 grass + 氶 + 灬 fire'],
  '炒': ['ショウ', 'いた(める) い(る)', 'stir-fry', '火 fire + 少'],
  '小': ['ショウ', 'ちい(さい) こ お', 'small', ''],
  '乳': ['ニュウ', 'ちち ち', 'milk, breast', ''],
  '製': ['セイ', '', 'manufacture', '制 + 衣 clothing'],
  '肉': ['ニク', '', 'meat', 'picture of a slice of meat'],
  '抹': ['マツ', '', 'rub, powder', '扌 hand + 末'],
  '氷': ['ヒョウ', 'こおり ひ', 'ice', ''],
  '福': ['フク', '', 'good fortune', '示 altar + 畐'],
  '団': ['ダン トン', '', 'group, round', '囗 enclosure + 寸'],
  '鍋': ['カ', 'なべ', 'pot, hot pot', '金 metal + 咼'],
};

// Entry: [word, "kana|romaji", meaning, spec, note]
// spec tokens (space separated) = "kanji:reading used here:type", type o=on, k=kun, i=whole-word (熟字訓/ateji), l=loanword.
// The reading covers the kanji part only; trailing okurigana is not included.
const GROUPS = [
  {
    id: 'food',
    name: 'Food',
    desc: 'Ramen, izakaya, yakitori, yakiniku, sushi, noodles, yōshoku, tempura, gyūdon, okonomiyaki',
    entries: [
      // Ramen: customization
      ["固め", "かため|katame", "Firm (noodles)", "固:かた:k", "固い (katai) = hard. The suffix め means ‘a bit toward ___’."],
      ["柔らかめ", "やわらかめ|yawarakame", "Soft (noodles)", "柔:やわ:k", "柔らかい (yawarakai): 柔 = やわ, and らかい is okurigana."],
      ["普通", "ふつう|futsū", "Normal / regular", "普:ふ:o 通:つう:o", "On + on. 通 alone is とお-る / かよ-う, but in compounds it is usually ツウ."],
      ["濃いめ", "こいめ|koime", "Strong / rich flavor", "濃:こ:k", "濃い (koi) = thick, strong. Opposite of 薄め."],
      ["薄め", "うすめ|usume", "Lighter flavor", "薄:うす:k", "薄い (usui) = thin, weak."],
      ["多め", "おおめ|ōme", "Extra / more", "多:おお:k", "多い (ōi) = many. 多 is タ in compounds like 多少 (tashō)."],
      ["少なめ", "すくなめ|sukuname", "Less / light", "少:すく:k", "少ない (sukunai): 少 = すく, ない is okurigana. 少 alone can also be すこ-し."],
      ["抜き", "ぬき|nuki", "Without / omit", "抜:ぬ:k", "抜く (nuku) = pull out. The noun 抜き means ‘with ___ removed’ (ねぎ抜き = no green onion)."],
      ["替え玉", "かえだま|kaedama", "Noodle refill", "替:か:k 玉:だま:k", "Rendaku: 玉 (tama) becomes だま after another element. 替える (kaeru) = to replace."],
      ["大盛り", "おおもり|ōmori", "Large portion", "大:おお:k 盛:もり:k", "盛る (moru) = heap up. 大 is ダイ in compounds like 大学 (daigaku)."],
      // Ramen items
      ["豚骨", "とんこつ|tonkotsu", "Pork-bone broth", "豚:とん:o 骨:こつ:o", "On + on. Alone: 豚 = ぶた, 骨 = ほね (kun)."],
      ["醤油", "しょうゆ|shōyu", "Soy sauce", "醤:しょう:o 油:ゆ:o", "On + on. 油 alone is あぶら (oil); ユ appears in compounds like 石油 (sekiyu)."],
      ["味噌", "みそ|miso", "Fermented soybean paste", "味噌:みそ:i", "Native word written with kanji chosen for sound/meaning. Learn it as a unit; 味 alone is あじ / ミ."],
      ["塩", "しお|shio", "Salt (also: salt seasoning at yakitori)", "塩:しお:k", "Lone kanji usually uses kun. The on reading エン appears in 塩分 (enbun, salt content)."],
      ["つけ麺", "つけめん|tsukemen", "Dipping noodles", "麺:めん:o", "つけ (from つける ‘to dip’) is kana, then 麺 (on)."],
      ["家系", "いえけい|iekei", "Yokohama-style pork-soy ramen", "家:いえ:k 系:けい:o", "Kun + on = 湯桶読み (yutō-yomi). 家 is カ / ケ in compounds (作家 sakka)."],
      ["叉焼", "チャーシュー|chāshū", "Braised pork (char siu)", "叉焼:チャーシュー:l", "Loan from Cantonese chāsīu. The kanji came with the word and are not read with Japanese on/kun."],
      ["味玉", "あじたま|ajitama", "Seasoned soft-boiled egg", "味:あじ:k 玉:たま:k", "Short for 味付け玉子 (seasoned egg). Kun + kun."],
      ["煮卵", "にたまご|nitamago", "Simmered egg", "煮:に:k 卵:たまご:k", "煮る (niru) = simmer. 卵 alone is たまご; the on reading ラン is in 卵黄 (ran’ō, yolk)."],
      ["海苔", "のり|nori", "Dried seaweed", "海苔:のり:i", "Whole-word reading (熟字訓). Don’t split it: 海 = カイ/うみ and 苔 = タイ/こけ."],
      ["木耳", "きくらげ|kikurage", "Wood ear mushroom", "木耳:きくらげ:i", "Whole-word reading (熟字訓): 木 (tree) + 耳 (ear), read きくらげ."],
      ["白飯", "しろめし|shiromeshi", "Plain white rice", "白:しろ:k 飯:めし:k", "Kun + kun. Formal reading: はくはん (hakuhan, on + on). Everyday: 白ご飯."],
      // Izakaya
      ["生ビール", "なまビール|nama bīru", "Draft beer", "生:なま:k", "生 has many readings: セイ / ショウ (on); い-きる, う-まれる, は-える, なま, き (kun). Context decides. ビール = beer (katakana)."],
      ["日本酒", "にほんしゅ|nihonshu", "Sake", "日:に:o 本:ほん:o 酒:しゅ:o", "On + on + on. 日本 can also be にっぽん (Nippon). 酒 alone is さけ."],
      ["焼酎", "しょうちゅう|shōchū", "Distilled spirit (shōchū)", "焼:しょう:o 酎:ちゅう:o", "On + on. 焼 alone is や-く; ショウ appears in 焼失 (shōshitsu, burned down)."],
      ["枝豆", "えだまめ|edamame", "Young soybeans in pods", "枝:えだ:k 豆:まめ:k", "Kun + kun. 豆 is ズ in 大豆 (daizu, soybean) and トウ in 豆腐 (tōfu)."],
      ["焼き鳥", "やきとり|yakitori", "Grilled chicken skewers", "焼:や:k 鳥:とり:k", "焼く (yaku) → 焼き (noun stem). 鳥 is チョウ in 白鳥 (hakuchō, swan)."],
      ["唐揚げ", "からあげ|karaage", "Japanese fried chicken", "唐:から:k 揚:あ:k", "揚げる (ageru) = deep-fry → 揚げ. 唐 = Tang China, hence ‘Chinese-style’ frying."],
      ["餃子", "ぎょうざ|gyōza", "Pan-fried dumplings", "餃子:ぎょうざ:l", "Loan from Chinese jiǎozi; the kanji came with the word. 子 alone is こ."],
      ["玉子焼き", "たまごやき|tamagoyaki", "Rolled omelet", "玉:たま:k 子:ご:k 焼:や:k", "Rendaku: 子 (ko) becomes ご. 玉子 is another way to write 卵."],
      ["刺身", "さしみ|sashimi", "Sliced raw fish", "刺:さし:k 身:み:k", "刺す (sasu) = pierce → 刺し; 身 = flesh. 身 is シン in 身体 (shintai, body)."],
      ["串焼き", "くしやき|kushiyaki", "Skewer-grilled food", "串:くし:k 焼:や:k", "Kun + kun. 串 is almost always read くし."],
      // Yakitori
      ["ねぎま", "ねぎま|negima", "Chicken & leek skewer", "", "Kana word. Sometimes 葱間: ねぎ (leek) + ま (between)."],
      ["もも", "もも|momo", "Chicken thigh", "", "Kana word. Kanji 腿 (もも; on タイ) is rare on menus."],
      ["つくね", "つくね|tsukune", "Chicken meatball", "", "Kana word, from つくねる ‘to knead / shape by hand’."],
      ["皮", "かわ|kawa", "Chicken skin", "皮:かわ:k", "Lone kanji, kun. On ヒ appears in 皮膚 (hifu, skin)."],
      ["砂肝", "すなぎも|sunagimo", "Gizzard", "砂:すな:k 肝:ぎも:k", "Rendaku: 肝 (kimo) becomes ぎも. 肝 is カン in 肝臓 (kanzō, liver)."],
      ["手羽先", "てばさき|tebasaki", "Chicken wing tip", "手:て:k 羽:ば:k 先:さき:k", "Rendaku: 羽 (ha) becomes ば. All kun."],
      ["軟骨", "なんこつ|nankotsu", "Cartilage", "軟:なん:o 骨:こつ:o", "On + on. 軟 alone is やわ-らかい (soft)."],
      // Yakiniku
      ["タレ", "タレ|tare", "Sweet soy glaze / sauce", "", "Kana word, from 垂れ (tare, ‘drip’)."],
      ["カルビ", "カルビ|karubi", "Boneless short rib", "", "Katakana loan from Korean galbi."],
      ["ロース", "ロース|rōsu", "Loin / chuck cut", "", "Katakana loan from English ‘roast’."],
      ["牛タン", "ぎゅうタン|gyūtan", "Beef tongue", "牛:ぎゅう:o", "On reading of 牛 + English ‘tongue’ in katakana. 牛 alone is うし."],
      ["ハラミ", "ハラミ|harami", "Skirt steak", "", "Katakana word, probably from 腹 (hara, belly)."],
      ["ホルモン", "ホルモン|horumon", "Offal / intestines", "", "Katakana word. Said to come from Kansai 放るもん (‘things to throw away’) or from ‘hormone’."],
      ["豚バラ", "ぶたバラ|butabara", "Pork belly", "豚:ぶた:k", "豚 alone is ぶた, but トン in 豚骨 / 豚カツ. バラ = rib / belly cut (kana)."],
      ["サンチュ", "サンチュ|sanchu", "Wrap lettuce", "", "Katakana loan from Korean."],
      ["網", "あみ|ami", "Grill grate / net", "網:あみ:k", "Lone kanji, kun. On モウ appears in 網膜 (mōmaku, retina)."],
      // Sushi
      ["鮪", "まぐろ|maguro", "Tuna", "鮪:まぐろ:k", "Fish kanji (魚 radical + sound part). Most fish kanji are only seen on menus and sushi cups."],
      ["赤身", "あかみ|akami", "Lean tuna cut", "赤:あか:k 身:み:k", "Kun + kun. 赤 is セキ in 赤道 (sekidō, equator)."],
      ["中トロ", "ちゅうトロ|chūtoro", "Medium-fatty tuna", "中:ちゅう:o", "On reading of 中 + トロ (from とろける ‘melt’). 中 alone is なか."],
      ["鮭", "さけ|sake", "Salmon (also サーモン)", "鮭:さけ:k", "Also read しゃけ. Not the same as 酒 (sake, alcohol): different kanji, same sound."],
      ["海老", "えび|ebi", "Shrimp / prawn", "海老:えび:i", "Whole-word reading (熟字訓). Don’t split it into 海 + 老."],
      ["烏賊", "いか|ika", "Squid", "烏賊:いか:i", "Whole-word reading (熟字訓). 烏 (crow) + 賊 (thief)."],
      ["蛸", "たこ|tako", "Octopus", "蛸:たこ:k", "Lone kanji, kun."],
      ["軍艦", "ぐんかん|gunkan", "Gunkan roll (‘warship’ sushi)", "軍:ぐん:o 艦:かん:o", "On + on. Literally ‘warship’, for the nori-wrapped shape."],
      ["サビ抜き", "サビぬき|sabi-nuki", "Without wasabi", "抜:ぬ:k", "サビ = wasabi (kana). 抜き = ‘without’."],
      // Noodles
      ["蕎麦", "そば|soba", "Buckwheat noodles", "蕎麦:そば:i", "Whole-word reading. 蕎 = キョウ, 麦 = バク / むぎ; neither gives ‘soba’ by itself."],
      ["うどん", "うどん|udon", "Thick wheat noodles", "", "Usually kana. Rare kanji spelling: 饂飩."],
      ["温かい", "あたたかい|atatakai", "Warm / hot", "温:あたた:k", "温 = あたた, かい is okurigana. On オン appears in 温泉 (onsen, hot spring)."],
      ["冷たい", "つめたい|tsumetai", "Cold", "冷:つめ:k", "冷 = つめ, たい is okurigana. On レイ appears in 冷蔵庫 (reizōko, fridge)."],
      ["ざる", "ざる|zaru", "Cold noodles on a bamboo tray", "", "Kana word. Kanji 笊 (bamboo basket) is rare."],
      ["かけ", "かけ|kake", "Hot noodles in broth", "", "Kana word, from 掛ける ‘to pour over’."],
      ["天ぷら", "てんぷら|tenpura", "Tempura", "天:てん:o", "From Portuguese; usually 天ぷら or 天麩羅 (kanji chosen for sound). 天 alone is あめ / あま."],
      ["狐", "きつね|kitsune", "Fox (kitsune udon: sweet fried tofu)", "狐:きつね:k", "Lone kanji, kun. Kitsune are said to love fried tofu."],
      ["狸", "たぬき|tanuki", "Raccoon dog (tanuki: tempura crumbs)", "狸:たぬき:k", "Lone kanji, kun."],
      // Yoshoku / tempura
      ["洋食", "ようしょく|yōshoku", "Western-style food", "洋:よう:o 食:しょく:o", "On + on. 食 alone is た-べる / く-う."],
      ["オムライス", "オムライス|omuraisu", "Omelet rice", "", "Katakana: omelet + rice (wasei-eigo)."],
      ["ハンバーグ", "ハンバーグ|hanbāgu", "Hamburger steak", "", "Katakana, from ‘Hamburg’."],
      ["海老フライ", "えびフライ|ebi furai", "Fried breaded shrimp", "海老:えび:i", "Whole-word 海老 (えび) + フライ (fry, katakana)."],
      ["豚カツ", "とんかつ|tonkatsu", "Deep-fried pork cutlet", "豚:とん:o", "On reading of 豚 + カツ (from ‘cutlet’). Often written とんかつ."],
      ["コロッケ", "コロッケ|korokke", "Croquette", "", "Katakana loan from French croquette."],
      ["カレーライス", "カレーライス|karē raisu", "Curry rice", "", "Katakana: curry + rice."],
      ["天丼", "てんどん|tendon", "Tempura rice bowl", "天:てん:o 丼:どん:o", "On + on. 丼 alone is どんぶり."],
      ["穴子", "あなご|anago", "Conger eel", "穴:あな:k 子:ご:k", "Rendaku: 子 (ko) becomes ご. 穴 alone = あな (hole)."],
      ["南瓜", "かぼちゃ|kabocha", "Kabocha squash", "南瓜:かぼちゃ:i", "Whole-word reading (熟字訓). Also read なんきん (nankin)."],
      ["茄子", "なす|nasu", "Eggplant", "茄子:なす:i", "Whole-word reading (熟字訓). 茄 is only used in this word."],
      ["天つゆ", "てんつゆ|tentsuyu", "Tempura dipping sauce", "天:てん:o", "つゆ (broth / dipping sauce) is usually kana."],
      // Gyudon
      ["牛丼", "ぎゅうどん|gyūdon", "Beef rice bowl", "牛:ぎゅう:o 丼:どん:o", "On + on. 牛 alone is うし."],
      ["並盛り", "なみもり|namimori", "Regular size", "並:なみ:k 盛:もり:k", "Kun + kun. 並 is ヘイ in 並行 (heikō, parallel)."],
      ["頭の大盛り", "あたまのおおもり|atama no ōmori", "Extra meat, regular rice", "頭:あたま:k 大:おお:k 盛:もり:k", "‘Large portion of the head (topping)’. 頭 is トウ / ズ in compounds (頭痛 zutsū)."],
      ["特盛り", "とくもり|tokumori", "Extra-large size", "特:とく:o 盛:もり:k", "On + kun = 重箱読み (jūbako-yomi)."],
      ["玉子", "たまご|tamago", "Egg (topping)", "玉:たま:k 子:ご:k", "Same word as 卵. Rendaku: 子 becomes ご."],
      ["紅生姜", "べにしょうが|beni shōga", "Red pickled ginger", "紅:べに:k 生姜:しょうが:i", "紅 (kun) + whole-word 生姜."],
      ["七味", "しちみ|shichimi", "Seven-spice chili blend", "七:しち:o 味:み:o", "On + on. 七 is also なな (kun) as in 七つ."],
      ["つゆだく", "つゆだく|tsuyu-daku", "Extra broth in the bowl", "", "Kana slang: つゆ (broth) + だく (‘lots’)."],
      // Okonomiyaki
      ["お好み焼き", "おこのみやき|okonomiyaki", "Savory griddled pancake", "好:この:k 焼:や:k", "お is a polite prefix; 好む (konomu) = like. 好 is コウ in 好物 (kōbutsu, favorite food)."],
      ["鉄板焼き", "てっぱんやき|teppanyaki", "Iron-griddle cooking", "鉄:てっ:o 板:ぱん:o 焼:や:k", "On + on + kun. テツ + ハン → てっぱん: ツ becomes small っ and ハ becomes パ."],
      ["豚玉", "ぶたたま|butatama", "Pork & egg okonomiyaki", "豚:ぶた:k 玉:たま:k", "Kun + kun."],
      ["海鮮焼き", "かいせんやき|kaisenyaki", "Seafood pancake", "海:かい:o 鮮:せん:o 焼:や:k", "On + on + kun. 海 alone is うみ."],
      ["モダン焼き", "モダンやき|modanyaki", "Okonomiyaki with yakisoba", "焼:や:k", "モダン (modern, katakana) + 焼き."],
      ["もんじゃ焼き", "もんじゃやき|monjayaki", "Runny Tokyo-style griddle batter", "焼:や:k", "もんじゃ (kana) + 焼き."],
      ["青のり", "あおのり|aonori", "Green seaweed flakes", "青:あお:k", "青 (kun) + のり (kana for 海苔)."],
      ["鰹節", "かつおぶし|katsuobushi", "Bonito flakes", "鰹:かつお:k 節:ぶし:k", "Rendaku: 節 (fushi) becomes ぶし. 節 is セツ in 季節 (kisetsu, season)."],
    ],
  },
  {
    id: 'menu',
    name: 'Menu Essentials',
    desc: 'Ordering, set meals, sushi pieces, hot pot, drinks, tastes, cooking verbs, allergens, sweets',
    entries: [
      // Ordering
      ["注文", "ちゅうもん|chūmon", "Order", "注:ちゅう:o 文:もん:o", "On + on. 文 is ブン in 文章 (bunshō) but モン here."],
      ["食券", "しょっけん|shokken", "Meal ticket (vending machine)", "食:しょっ:o 券:けん:o", "On + on. ショク + ケン → しょっけん: ク becomes small っ before a K sound."],
      ["定食", "ていしょく|teishoku", "Set meal", "定:てい:o 食:しょく:o", "On + on. 定 is also ジョウ (as in 定規 jōgi)."],
      ["単品", "たんぴん|tanpin", "À la carte item", "単:たん:o 品:ぴん:o", "On + on. 品 is ヒン, but after ん it becomes ぴん."],
      ["食べ放題", "たべほうだい|tabehōdai", "All-you-can-eat", "食:た:k 放:ほう:o 題:だい:o", "食べる stem + 放題 (on + on), ‘as much as you like’."],
      ["飲み放題", "のみほうだい|nomihōdai", "All-you-can-drink", "飲:の:k 放:ほう:o 題:だい:o", "飲む stem + 放題. Same pattern as 食べ放題."],
      ["持ち帰り", "もちかえり|mochikaeri", "Takeout", "持:も:k 帰:かえ:k", "Two verb stems joined: 持つ + 帰る → ‘take and return home’."],
      ["お会計", "おかいけい|okaikei", "The bill", "会:かい:o 計:けい:o", "お is a polite prefix. 会計 is on + on."],
      ["税込", "ぜいこみ|zeikomi", "Tax included", "税:ぜい:o 込:こみ:k", "On + kun = 重箱読み. 込 is a Japan-made kanji with no on reading."],
      ["禁煙席", "きんえんせき|kin’enseki", "Non-smoking seat", "禁:きん:o 煙:えん:o 席:せき:o", "Three on readings. 禁煙 = ‘ban smoke’."],
      ["喫煙席", "きつえんせき|kitsuenseki", "Smoking seat", "喫:きつ:o 煙:えん:o 席:せき:o", "喫 is rare outside this word and 喫茶店 (kissaten, café)."],
      ["お代わり", "おかわり|okawari", "Refill / seconds", "代:か:k", "代わる (kawaru) = take the place of. 代 is ダイ in 代金 (daikin, price)."],
      ["追加", "ついか|tsuika", "Add-on / additional order", "追:つい:o 加:か:o", "On + on."],
      ["予約", "よやく|yoyaku", "Reservation", "予:よ:o 約:やく:o", "On + on."],
      ["無料", "むりょう|muryō", "Free of charge", "無:む:o 料:りょう:o", "On + on. The kun reading of 無 is な-い."],
      // Rice bowls / set meal
      ["寿司", "すし|sushi", "Sushi", "寿司:すし:i", "Ateji: 寿 (longevity) + 司 (manage) chosen for good luck and sound, not meaning. Learn as a unit."],
      ["親子丼", "おやこどん|oyakodon", "Chicken & egg bowl", "親:おや:k 子:こ:k 丼:どん:o", "Kun + kun + on. ‘Parent and child’ (chicken and egg)."],
      ["カツ丼", "カツどん|katsudon", "Pork cutlet bowl", "丼:どん:o", "カツ (cutlet, katakana) + 丼 (on)."],
      ["海鮮丼", "かいせんどん|kaisendon", "Seafood bowl", "海:かい:o 鮮:せん:o 丼:どん:o", "On + on + on. 鮮 = fresh."],
      ["味噌汁", "みそしる|misoshiru", "Miso soup", "味噌:みそ:i 汁:しる:k", "Whole-word 味噌 + kun 汁. 汁 is ジュウ in 果汁 (kajū, fruit juice)."],
      ["漬物", "つけもの|tsukemono", "Pickles", "漬:つけ:k 物:もの:k", "Kun + kun. 漬ける (tsukeru) = pickle. 物 is ブツ / モツ in 動物, 食物."],
      ["納豆", "なっとう|nattō", "Fermented soybeans", "納:なっ:o 豆:とう:o", "On + on with small っ: 納 is ノウ elsewhere but ナッ here. Learn as a set word."],
      ["卵かけご飯", "たまごかけごはん|tamago kake gohan", "Raw egg over rice", "卵:たまご:k 飯:はん:o", "卵 (kun) + かけ (from かける ‘pour over’) + ご (polite) + 飯 (on)."],
      ["焼き魚", "やきざかな|yakizakana", "Grilled fish", "焼:や:k 魚:ざかな:k", "Rendaku: 魚 (sakana) becomes ざかな. 魚 is ギョ in 魚介 (gyokai, seafood)."],
      ["鰻", "うなぎ|unagi", "Eel", "鰻:うなぎ:k", "Fish kanji: 魚 radical + 曼."],
      ["ご飯", "ごはん|gohan", "Cooked rice / a meal", "飯:はん:o", "ご is a polite prefix (御). 飯 alone can be めし (blunt, masculine)."],
      // Sushi pieces
      ["握り", "にぎり|nigiri", "Hand-pressed sushi", "握:にぎ:k", "握る (nigiru) = grip. On アク appears in 握手 (akushu, handshake)."],
      ["巻き", "まき|maki", "Rolled sushi", "巻:ま:k", "巻く (maku) = roll. On カン appears in 全巻 (zenkan, complete set)."],
      ["鯛", "たい|tai", "Sea bream", "鯛:たい:k", "Fish kanji: 魚 + 周. A lucky fish (めでたい)."],
      ["鰤", "ぶり|buri", "Yellowtail", "鰤:ぶり:k", "Fish kanji: 魚 + 師. Kun only."],
      ["鯖", "さば|saba", "Mackerel", "鯖:さば:k", "Fish kanji: 魚 + 青."],
      ["雲丹", "うに|uni", "Sea urchin", "雲丹:うに:i", "Ateji / whole-word reading. 雲 (cloud) + 丹 (red). Often written うに or ウニ."],
      ["いくら", "いくら|ikura", "Salmon roe", "", "Usually katakana イクラ; from Russian ikra."],
      ["帆立", "ほたて|hotate", "Scallop", "帆:ほ:k 立:たて:k", "Kun + kun: 帆 (sail) + 立つ (tatsu); the shell looks like a raised sail."],
      ["回転寿司", "かいてんずし|kaiten-zushi", "Conveyor-belt sushi", "回:かい:o 転:てん:o 寿司:ずし:i", "Rendaku: すし becomes ずし. ‘Rotating sushi’."],
      ["山葵", "わさび|wasabi", "Wasabi", "山葵:わさび:i", "Whole-word reading; usually kana. 山 (mountain) + 葵 (hollyhock)."],
      ["生姜", "しょうが|shōga", "Ginger (sushi ginger is ガリ)", "生姜:しょうが:i", "Whole-word reading. 姜 is almost only seen in this word."],
      // Hot pot
      ["鍋", "なべ|nabe", "Hot pot / pot", "鍋:なべ:k", "Lone kanji, kun. Appears in dish names: 寄せ鍋 (yosenabe)."],
      ["しゃぶしゃぶ", "しゃぶしゃぶ|shabu-shabu", "Swish-swish hot pot", "", "Kana. Imitates the sound of swishing meat in broth."],
      ["すき焼き", "すきやき|sukiyaki", "Sukiyaki", "焼:や:k", "すき is usually kana. 焼く → 焼き."],
      ["おでん", "おでん|oden", "Oden (simmered hot pot)", "", "Kana. From 田楽 (dengaku) with the polite prefix お."],
      // Drinks
      ["ビール", "ビール|bīru", "Beer", "", "Katakana loan (Dutch bier). Sometimes written 麦酒 (barley + alcohol) but still read ビール."],
      ["ハイボール", "ハイボール|haibōru", "Highball (whisky & soda)", "", "Katakana loan."],
      ["レモンサワー", "レモンサワー|remon sawā", "Lemon sour (shōchū cocktail)", "", "Katakana: lemon + sour."],
      ["烏龍茶", "ウーロンちゃ|ūroncha", "Oolong tea", "烏龍:ウーロン:l 茶:ちゃ:o", "烏龍 is read ウーロン (Chinese wūlóng) and 茶 is the on reading チャ."],
      ["梅酒", "うめしゅ|umeshu", "Plum wine", "梅:うめ:k 酒:しゅ:o", "Kun + on = 湯桶読み. 酒 is しゅ here, not さけ."],
      ["熱燗", "あつかん|atsukan", "Hot sake", "熱:あつ:k 燗:かん:o", "Kun + on = 湯桶読み. 燗 appears only in this word family."],
      ["冷酒", "れいしゅ|reishu", "Chilled sake", "冷:れい:o 酒:しゅ:o", "On + on. Compare 冷たい (tsumetai, kun)."],
      ["お茶", "おちゃ|ocha", "Tea", "茶:ちゃ:o", "お is a polite prefix. 茶 is チャ / サ (喫茶 kissa)."],
      ["お水", "おみず|omizu", "Water", "水:みず:k", "お prefix + kun 水. On スイ appears in 水曜日 (suiyōbi, Wednesday)."],
      // Tastes
      ["辛い", "からい|karai", "Spicy / salty", "辛:から:k", "Two kun readings: からい (spicy) and つらい (painful). Context decides."],
      ["甘い", "あまい|amai", "Sweet", "甘:あま:k", "On カン appears in 甘味 (kanmi, sweet taste)."],
      ["酸っぱい", "すっぱい|suppai", "Sour", "酸:す:k", "酸 = す, っぱい is okurigana. On サン appears in 酸素 (sanso, oxygen)."],
      ["苦い", "にがい|nigai", "Bitter", "苦:にが:k", "On ク appears in 苦労 (kurō, hardship)."],
      ["美味しい", "おいしい|oishii", "Delicious", "美味:おい:i", "Whole-word reading (美味 = おい). The on + on reading びみ (bimi) means ‘fine flavor’."],
      // Cooking words
      ["生", "なま|nama", "Raw / fresh", "生:なま:k", "Same kanji as 生ビール. Other readings: セイ (生活), ショウ (一生), い-きる, う-まれる."],
      ["焼く", "やく|yaku", "To grill / bake", "焼:や:k", "Kun with okurigana く. On ショウ appears in 焼酎."],
      ["煮る", "にる|niru", "To simmer", "煮:に:k", "Kun with okurigana る."],
      ["揚げる", "あげる|ageru", "To deep-fry", "揚:あ:k", "揚 = あ, げる is okurigana. On ヨウ is rare."],
      ["蒸す", "むす|musu", "To steam", "蒸:む:k", "On ジョウ appears in 蒸気 (jōki, steam)."],
      ["炒める", "いためる|itameru", "To stir-fry", "炒:いた:k", "炒 = いた, める is okurigana."],
      // Allergens
      ["卵", "たまご|tamago", "Egg", "卵:たまご:k", "On ラン appears in 卵黄 (ran’ō, yolk)."],
      ["小麦", "こむぎ|komugi", "Wheat", "小:こ:k 麦:むぎ:k", "Kun + kun. On readings: 小 = ショウ, 麦 = バク."],
      ["乳製品", "にゅうせいひん|nyūseihin", "Dairy products", "乳:にゅう:o 製:せい:o 品:ひん:o", "Three on readings. 乳 alone is ちち."],
      ["肉", "にく|niku", "Meat", "肉:にく:o", "A lone kanji read with its on reading; 肉 has no kun reading. Always check, never assume."],
      ["魚", "さかな|sakana", "Fish", "魚:さかな:k", "Kun. On ギョ appears in 魚介 (gyokai, seafood)."],
      ["食べられません", "たべられません|taberaremasen", "I can’t eat (it)", "食:た:k", "食べる + られる (potential) + ません (polite negative)."],
      ["アレルギー", "アレルギー|arerugī", "Allergy", "", "Katakana loan from German Allergie."],
      // Sweets
      ["抹茶", "まっちゃ|matcha", "Matcha", "抹:まっ:o 茶:ちゃ:o", "On + on with small っ: マツ + チャ → まっちゃ."],
      ["かき氷", "かきごおり|kakigōri", "Shaved ice", "氷:ごおり:k", "Rendaku: 氷 (kōri) becomes ごおり. かき (‘scraped’) is kana."],
      ["たい焼き", "たいやき|taiyaki", "Fish-shaped cake", "焼:や:k", "たい = 鯛 (sea bream) in kana, + 焼き."],
      ["大福", "だいふく|daifuku", "Filled rice cake", "大:だい:o 福:ふく:o", "On + on. ‘Great luck’."],
      ["団子", "だんご|dango", "Sweet dumpling", "団子:だんご:i", "Treat as a set word: 子 is not read ご in normal on/kun."],
    ],
  },
];
